services:
  emby-migrator:
    image: ${EMBY_MIGRATOR_IMAGE:-czppwa/emby-migrator:latest}
    container_name: emby-migrator
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      EMBY_MIGRATOR_PASSWORD: password
    volumes:
      - ${EMBY_MIGRATOR_DATA_DIR:-/opt/emby-migrator/data}:/data
      - ${EMBY_MIGRATOR_CONFIG_DIR:-/opt/emby-migrator/config}:/config
    restart: unless-stopped
